DROP TABLE ELISM_ADMIN.T_BOARD CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_BOARD
(
  T_UID         NUMBER                          NOT NULL,
  BOARD_NO      NUMBER                          NOT NULL,
  TITLE         VARCHAR2(500 CHAR)              NOT NULL,
  HTML          CLOB,
  SAVE_FLAG     CHAR(1 CHAR),
  DELETE_FLAG   CHAR(1 CHAR)                    DEFAULT 'N'                   NOT NULL,
  ATTACH_CNT    NUMBER(10),
  VISIT_CNT     NUMBER                          DEFAULT 0                     NOT NULL,
  PARENT_UID    NUMBER                          NOT NULL,
  STEP          NUMBER,
  CHILD_UID     NUMBER,
  DOWNLOAD_CNT  NUMBER                          DEFAULT 0                     NOT NULL,
  CREATE_ID     VARCHAR2(50 CHAR)               NOT NULL,
  CREATE_DT     DATE                            NOT NULL,
  UPDATE_DT     DATE,
  UPDATE_ID     VARCHAR2(50 BYTE)
)
LOB (HTML) STORE AS (
  TABLESPACE  ELISM
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ELISM_ADMIN.T_BOARD_IDX_UID_BOARDNO ON ELISM_ADMIN.T_BOARD
(T_UID, BOARD_NO)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
DROP TABLE ELISM_ADMIN.T_BOARD_FILE CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_BOARD_FILE
(
  BOARD_NO     NUMBER,
  FILE_INDEX   NUMBER(10)                       NOT NULL,
  FILE_SIZE    NUMBER                           NOT NULL,
  FILE_TYPE    VARCHAR2(30 CHAR)                NOT NULL,
  FILE_NAME    VARCHAR2(255 CHAR)               NOT NULL,
  FILE_PATH    VARCHAR2(255 CHAR)               NOT NULL,
  FOLDER_NAME  NUMBER                           NOT NULL,
  DELETE_FLAG  CHAR(1 BYTE)                     DEFAULT 'N',
  CREATE_ID    VARCHAR2(50 BYTE),
  CREATE_DT    DATE,
  UPDATE_ID    VARCHAR2(50 BYTE),
  UPDATE_DT    DATE
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
ALTER TABLE ELISM_ADMIN.T_CODE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_CODE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_CODE_DETAIL
(
  CODE_ID    VARCHAR2(10 BYTE)                  NOT NULL,
  CODE_DESC  VARCHAR2(10 BYTE)                  NOT NULL,
  CODE_NM    VARCHAR2(100 BYTE)                 NOT NULL,
  CREATE_ID  VARCHAR2(128 BYTE),
  CREATE_DT  TIMESTAMP(6),
  UPDATE_ID  VARCHAR2(128 BYTE),
  UPDATE_DT  TIMESTAMP(6),
  USAGE_YN   CHAR(1 BYTE)                       DEFAULT 'Y'
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_CODE_DETAIL_PK ON ELISM_ADMIN.T_CODE_DETAIL
(CODE_ID, CODE_DESC)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_CODE_DETAIL ADD (
  CONSTRAINT T_CODE_DETAIL_PK
  PRIMARY KEY
  (CODE_ID, CODE_DESC)
  USING INDEX ELISM_ADMIN.T_CODE_DETAIL_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_CODE_MASTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_CODE_MASTER CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_CODE_MASTER
(
  CODE_ID    VARCHAR2(10 BYTE)                  NOT NULL,
  CODE_NM    VARCHAR2(60 BYTE)                  NOT NULL,
  USAGE_YN   CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL,
  CREATE_DT  DATE,
  CREATE_ID  VARCHAR2(20 BYTE),
  UPDATE_DT  DATE,
  UPDATE_ID  VARCHAR2(20 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_CODE_INFO_PK ON ELISM_ADMIN.T_CODE_MASTER
(CODE_ID)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_CODE_MASTER ADD (
  CONSTRAINT T_CODE_INFO_PK
  PRIMARY KEY
  (CODE_ID)
  USING INDEX ELISM_ADMIN.T_CODE_INFO_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_COMPANY_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_COMPANY_INFO CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_COMPANY_INFO
(
  COMPANY_CD  VARCHAR2(20 BYTE)                 NOT NULL,
  COMPANY_NM  NVARCHAR2(128),
  USAGE_YN    CHAR(1 BYTE),
  UPDATE_DT   TIMESTAMP(6),
  UPDATE_ID   VARCHAR2(128 BYTE),
  CREATE_DT   TIMESTAMP(6),
  CREATE_ID   VARCHAR2(128 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_COMPANY_INFO_PK ON ELISM_ADMIN.T_COMPANY_INFO
(COMPANY_CD)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_COMPANY_INFO ADD (
  CONSTRAINT T_COMPANY_INFO_PK
  PRIMARY KEY
  (COMPANY_CD)
  USING INDEX ELISM_ADMIN.T_COMPANY_INFO_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_DEPT_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_DEPT_INFO CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_DEPT_INFO
(
  DEPT_CD     VARCHAR2(20 BYTE)                 DEFAULT NULL                  NOT NULL,
  DEPT_NM     VARCHAR2(60 BYTE)                 NOT NULL,
  REMARK      NVARCHAR2(20),
  UP_DEPT_CD  VARCHAR2(20 BYTE)                 NOT NULL,
  USAGE_YN    NCHAR(1)                          DEFAULT 'Y'                   NOT NULL,
  CREATE_ID   NVARCHAR2(128),
  CREATE_DT   TIMESTAMP(6),
  UPDATE_ID   NVARCHAR2(128),
  UPDATE_DT   TIMESTAMP(6),
  COMPANY_CD  VARCHAR2(20 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.DEPT_INFO_PK ON ELISM_ADMIN.T_DEPT_INFO
(DEPT_CD)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_DEPT_INFO ADD (
  CONSTRAINT GROUP_INFO_PK
  PRIMARY KEY
  (DEPT_CD)
  USING INDEX ELISM_ADMIN.DEPT_INFO_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_MENU_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_MENU_INFO CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_MENU_INFO
(
  MENU_ID         NUMBER                        NOT NULL,
  MENU_NM         NVARCHAR2(64),
  PARENT_MENU_ID  NUMBER,
  MENU_ORDER      NUMBER,
  MENU_DESC       NVARCHAR2(512),
  MENU_DEPTH      NUMBER                        NOT NULL,
  MENU_URL        VARCHAR2(256 BYTE),
  AUTH_PTTRN      VARCHAR2(256 BYTE),
  CREATE_DT       TIMESTAMP(6),
  CREATE_ID       VARCHAR2(128 BYTE),
  UPDATE_DT       TIMESTAMP(6),
  UPDATE_ID       VARCHAR2(128 BYTE),
  USAGE_YN        NCHAR(1)                      DEFAULT 'Y'
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.PK_T_MENU_INFO ON ELISM_ADMIN.T_MENU_INFO
(MENU_ID)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_MENU_INFO ADD (
  CONSTRAINT PK_T_MENU_INFO
  PRIMARY KEY
  (MENU_ID)
  USING INDEX ELISM_ADMIN.PK_T_MENU_INFO
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_MENU_ROLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_MENU_ROLE CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_MENU_ROLE
(
  MENU_ID    VARCHAR2(30 BYTE)                  NOT NULL,
  ROLE_CD    VARCHAR2(30 BYTE)                  NOT NULL,
  UPDATE_DT  TIMESTAMP(6),
  UPDATE_ID  VARCHAR2(128 BYTE),
  CREATE_DT  TIMESTAMP(6),
  CREATE_ID  VARCHAR2(128 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_MENU_ROLE_PK ON ELISM_ADMIN.T_MENU_ROLE
(MENU_ID, ROLE_CD)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_MENU_ROLE ADD (
  CONSTRAINT T_MENU_ROLE_PK
  PRIMARY KEY
  (MENU_ID, ROLE_CD)
  USING INDEX ELISM_ADMIN.T_MENU_ROLE_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_ROLE_HIERARCHY
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_ROLE_HIERARCHY CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_ROLE_HIERARCHY
(
  PARENT_ROLE    VARCHAR2(30 BYTE)              NOT NULL,
  CHILDREN_ROLE  VARCHAR2(30 BYTE)              NOT NULL,
  UPDATE_DT      TIMESTAMP(6),
  UPDATE_ID      VARCHAR2(128 BYTE),
  CREATE_DT      TIMESTAMP(6),
  CREATE_ID      VARCHAR2(128 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_ROLE_HIERARCHY_PK ON ELISM_ADMIN.T_ROLE_HIERARCHY
(PARENT_ROLE, CHILDREN_ROLE)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_ROLE_HIERARCHY ADD (
  CONSTRAINT T_ROLE_HIERARCHY_PK
  PRIMARY KEY
  (PARENT_ROLE, CHILDREN_ROLE)
  USING INDEX ELISM_ADMIN.T_ROLE_HIERARCHY_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_ROLE_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_ROLE_INFO CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_ROLE_INFO
(
  ROLE_CD    VARCHAR2(30 BYTE)                  NOT NULL,
  ROLE_NM    NVARCHAR2(20),
  ROLE_DESC  NVARCHAR2(20),
  UPDATE_DT  TIMESTAMP(6),
  UPDATE_ID  VARCHAR2(128 BYTE),
  CREATE_DT  TIMESTAMP(6),
  CREATE_ID  VARCHAR2(128 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_ROLE_INFO_PK ON ELISM_ADMIN.T_ROLE_INFO
(ROLE_CD)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_ROLE_INFO ADD (
  CONSTRAINT T_ROLE_INFO_PK
  PRIMARY KEY
  (ROLE_CD)
  USING INDEX ELISM_ADMIN.T_ROLE_INFO_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_USER_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_USER_INFO CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_USER_INFO
(
  USER_ID       VARCHAR2(20 BYTE)               NOT NULL,
  USER_NM       VARCHAR2(50 BYTE)               NOT NULL,
  PWD           VARCHAR2(200 BYTE)              NOT NULL,
  PWD_HINT      VARCHAR2(100 BYTE),
  PWD_CNSR      VARCHAR2(100 BYTE),
  JOB_CD        VARCHAR2(50 BYTE),
  POSITION_CD   VARCHAR2(50 BYTE),
  TITLE_CD      VARCHAR2(50 BYTE),
  EMP_NO        VARCHAR2(200 BYTE),
  HIRE_DT       DATE,
  PROMOTION_DT  DATE,
  DEPT_CD       VARCHAR2(20 BYTE),
  DEPT_NM       NVARCHAR2(100),
  EMAIL         VARCHAR2(100 BYTE),
  ZIP_CD        VARCHAR2(10 BYTE),
  ADR1          NVARCHAR2(100),
  ADR2          NVARCHAR2(100),
  ADR3          NVARCHAR2(100),
  MOBILE_NO     VARCHAR2(15 BYTE),
  TEL_NO        VARCHAR2(15 BYTE),
  COM_TEL_NO    VARCHAR2(15 BYTE),
  FAX_NO        VARCHAR2(15 BYTE),
  USER_ORDER    NUMBER,
  USAGE_YN      CHAR(1 BYTE),
  USER_ST       CHAR(1 BYTE),
  CREATE_DT     TIMESTAMP(6),
  CREATE_ID     VARCHAR2(128 BYTE),
  UPDATE_DT     TIMESTAMP(6),
  UPDATE_ID     VARCHAR2(128 BYTE),
  COMPANY_CD    VARCHAR2(20 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_USER_INFO_PK ON ELISM_ADMIN.T_USER_INFO
(USER_ID)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_USER_INFO ADD (
  CONSTRAINT T_USER_INFO_PK
  PRIMARY KEY
  (USER_ID)
  USING INDEX ELISM_ADMIN.T_USER_INFO_PK
  ENABLE VALIDATE);
ALTER TABLE ELISM_ADMIN.T_USER_ROLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE ELISM_ADMIN.T_USER_ROLE CASCADE CONSTRAINTS;

CREATE TABLE ELISM_ADMIN.T_USER_ROLE
(
  ROLE_CD      VARCHAR2(20 BYTE)                NOT NULL,
  TARGET_ID    VARCHAR2(20 BYTE)                NOT NULL,
  TARGET_TYPE  CHAR(1 BYTE)                     NOT NULL,
  UPDATE_DT    TIMESTAMP(6),
  UPDATE_ID    VARCHAR2(128 BYTE),
  CREATE_DT    TIMESTAMP(6),
  CREATE_ID    VARCHAR2(128 BYTE)
)
TABLESPACE ELISM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ELISM_ADMIN.T_USER_ROLE_PK ON ELISM_ADMIN.T_USER_ROLE
(ROLE_CD, TARGET_ID, TARGET_TYPE)
LOGGING
TABLESPACE ELISM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ELISM_ADMIN.T_USER_ROLE ADD (
  CONSTRAINT T_USER_ROLE_PK
  PRIMARY KEY
  (ROLE_CD, TARGET_ID, TARGET_TYPE)
  USING INDEX ELISM_ADMIN.T_USER_ROLE_PK
  ENABLE VALIDATE);
